apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-storage-deployment
  labels:
    app: admission-webhook-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook-storage
  template:
    metadata:
      labels:
        app: admission-webhook-storage
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccount: admission-webhook-storage-sa
      containers:
        - name: admission-webhook-storage
          image: kubeoperator/admission-webhook/admission-webhook-storage:v1
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: kube-config
              mountPath: /root/.kube/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-storage-certs
        - name: kube-config
          hostPath:
            path: /root/.kube/config