apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-webhook-storage-sa
#  labels:
#    app: admission-webhook-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-webhook-storage-cr
  labels:
    app: admission-webhook-storage
rules:
- apiGroups:
  - sugon.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - pvc
  - persistentVolumeClaim
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-webhook-storage-crb
  labels:
    app: admission-webhook-storage
subjects:
- kind: ServiceAccount
  name: admission-webhook-storage-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-webhook-storage-cr
