apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-storage-cfg
  labels:
    app: admission-webhook-storage
webhooks:
  - name: quota-storage.sugon.com
    clientConfig:
      service:
        name: admission-webhook-storage-svc
        namespace: default
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE", "DELETE"]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["persistentvolumeclaims"]

#    namespaceSelector:
#      matchLabels:
#        admission-webhook-example: enabled
